<a href="https://colab.research.google.com/github/KabichNeu/Deep-Learning-with-Pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [ ]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 4.0
points[5] = 2.0

In [ ]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 4.0, 2.0 ])
points

tensor([4., 1., 5., 3., 4., 2.])

In [ ]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points.shape

torch.Size([3, 2])

In [ ]:
torch.Size([3, 2])

torch.Size([3, 2])

In [ ]:
points = torch.zeros(3, 2)

In [ ]:
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points[0,1]

tensor(1.)

In [ ]:
some_list = list(range(6))
some_list[:]

[0, 1, 2, 3, 4, 5]

In [ ]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [ ]:
some_list[1:4]

[1, 2, 3]

In [ ]:
some_list[1:]

[1, 2, 3, 4, 5]

In [ ]:
some_list[:4]

[0, 1, 2, 3]

In [ ]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [ ]:
some_list[1:4:2]

[1, 3]

In [ ]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [ ]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [ ]:
points[1:,0]

tensor([5., 2.])

In [ ]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [ ]:
#named tensors

In [ ]:
img_t = torch.randn(3,5,5)     #shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [ ]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [ ]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [ ]:
batch_t

tensor([[[[-1.0953e+00, -6.5561e-01, -9.6715e-01,  9.0681e-01,  8.5088e-01],
          [ 8.7646e-02,  1.3453e+00,  2.0663e-01, -1.1431e+00,  1.0181e-01],
          [-8.6459e-01, -5.2628e-01, -1.6267e+00, -6.8708e-01,  2.6783e+00],
          [ 9.0820e-03, -1.6630e-01,  6.6823e-01,  1.8339e-01,  9.1383e-01],
          [ 6.3329e-01,  3.4878e-01, -2.1296e-01, -4.6035e-01, -1.1840e+00]],

         [[-4.1466e+00,  5.8014e-01, -2.3229e+00,  1.5792e+00, -1.1647e+00],
          [ 1.3202e+00, -9.6170e-01,  8.0649e-01,  1.1667e+00, -2.1222e+00],
          [-3.9483e-01,  1.0011e+00,  5.1946e-01,  2.9938e-02, -8.9928e-01],
          [ 5.0443e-01,  6.7464e-01, -2.1096e-02,  1.2518e+00, -1.8066e+00],
          [ 4.5830e-02,  9.6847e-01,  8.0153e-01, -2.2291e-01,  1.5157e+00]],

         [[-1.9961e-01, -1.4214e+00,  7.6569e-01, -7.0517e-01, -9.2171e-01],
          [ 1.3612e-01,  1.1591e+00,  3.8927e-01, -5.6957e-01, -4.0267e-02],
          [ 7.8979e-01,  1.1372e+00,  5.4879e-01, -9.5862e-04,  4.6170e-

In [ ]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [ ]:
img_gray_naive

tensor([[ 0.3035, -1.1056, -0.0505,  0.3001,  1.0878],
        [ 0.8350, -1.0942, -0.0632, -0.6412,  0.0816],
        [-0.2070, -0.3575, -0.3154, -0.1064, -0.0751],
        [-0.5918,  0.2373, -1.1803,  0.3372, -0.2006],
        [ 0.4775,  0.1566, -0.4378,  0.1607, -1.3698]])

In [ ]:
img_t

tensor([[[ 0.3356, -0.8368,  0.9585,  0.3107,  1.1607],
         [ 0.7640, -2.4406,  0.5948, -0.0535,  0.9515],
         [ 0.6793, -2.6207, -0.1811,  0.3999, -1.3563],
         [-2.0746, -0.7560, -1.4531,  0.7284,  1.5534],
         [ 0.0893, -0.1462, -1.1186, -0.4207, -1.9426]],

        [[-0.0795, -1.9646,  0.4900,  0.6147, -0.1530],
         [ 1.2396,  0.5299, -0.9229, -0.5191,  0.0099],
         [-1.0873,  0.4859, -0.0771, -0.3918,  0.1291],
         [-0.1759, -0.3543, -1.6640,  0.8235, -0.1571],
         [ 1.3481,  1.1867, -0.6317,  0.6567, -2.7418]],

        [[ 0.6545, -0.5155, -1.6000, -0.0249,  2.2556],
         [ 0.5014, -1.3717,  0.1384, -1.3508, -0.7166],
         [-0.2129,  1.0622, -0.6879, -0.3271,  1.0020],
         [ 0.4752,  1.8221, -0.4238, -0.5404, -1.9981],
         [-0.0050, -0.5706,  0.4367,  0.2462,  0.5751]]])

In [ ]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [ ]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [ ]:
img_weights

tensor([[[ 7.1343e-02, -1.7791e-01,  2.0377e-01,  6.6046e-02,  2.4676e-01],
         [ 1.6242e-01, -5.1888e-01,  1.2645e-01, -1.1381e-02,  2.0228e-01],
         [ 1.4441e-01, -5.5716e-01, -3.8508e-02,  8.5018e-02, -2.8835e-01],
         [-4.4107e-01, -1.6072e-01, -3.0893e-01,  1.5487e-01,  3.3025e-01],
         [ 1.8982e-02, -3.1076e-02, -2.3781e-01, -8.9447e-02, -4.1300e-01]],

        [[-5.6860e-02, -1.4051e+00,  3.5048e-01,  4.3961e-01, -1.0941e-01],
         [ 8.8654e-01,  3.7898e-01, -6.6002e-01, -3.7124e-01,  7.0909e-03],
         [-7.7761e-01,  3.4749e-01, -5.5165e-02, -2.8024e-01,  9.2330e-02],
         [-1.2579e-01, -2.5339e-01, -1.1901e+00,  5.8899e-01, -1.1233e-01],
         [ 9.6418e-01,  8.4872e-01, -4.5179e-01,  4.6964e-01, -1.9610e+00]],

        [[ 4.7257e-02, -3.7219e-02, -1.1552e-01, -1.8010e-03,  1.6285e-01],
         [ 3.6200e-02, -9.9040e-02,  9.9915e-03, -9.7531e-02, -5.1739e-02],
         [-1.5374e-02,  7.6694e-02, -4.9663e-02, -2.3618e-02,  7.2341e-02],
        

In [ ]:
batch_weights

tensor([[[[-2.3286e-01, -1.3938e-01, -2.0562e-01,  1.9279e-01,  1.8090e-01],
          [ 1.8634e-02,  2.8601e-01,  4.3930e-02, -2.4302e-01,  2.1645e-02],
          [-1.8381e-01, -1.1189e-01, -3.4584e-01, -1.4607e-01,  5.6940e-01],
          [ 1.9308e-03, -3.5355e-02,  1.4207e-01,  3.8988e-02,  1.9428e-01],
          [ 1.3464e-01,  7.4151e-02, -4.5275e-02, -9.7870e-02, -2.5173e-01]],

         [[-2.9656e+00,  4.1492e-01, -1.6614e+00,  1.1295e+00, -8.3300e-01],
          [ 9.4421e-01, -6.8781e-01,  5.7680e-01,  8.3446e-01, -1.5178e+00],
          [-2.8238e-01,  7.1600e-01,  3.7152e-01,  2.1412e-02, -6.4317e-01],
          [ 3.6077e-01,  4.8250e-01, -1.5088e-02,  8.9529e-01, -1.2921e+00],
          [ 3.2778e-02,  6.9265e-01,  5.7325e-01, -1.5943e-01,  1.0841e+00]],

         [[-1.4412e-02, -1.0262e-01,  5.5283e-02, -5.0913e-02, -6.6547e-02],
          [ 9.8280e-03,  8.3684e-02,  2.8105e-02, -4.1123e-02, -2.9073e-03],
          [ 5.7023e-02,  8.2106e-02,  3.9623e-02, -6.9212e-05,  3.3335e-

In [ ]:
img_gray_weighted

tensor([[ 0.0617, -1.6202,  0.4387,  0.5039,  0.3002],
        [ 1.0852, -0.2389, -0.5236, -0.4802,  0.1576],
        [-0.6486, -0.1330, -0.1433, -0.2188, -0.1237],
        [-0.5325, -0.2826, -1.5296,  0.7048,  0.0737],
        [ 0.9828,  0.7764, -0.6581,  0.3980, -2.3324]])

In [ ]:
batch_gray_weighted

tensor([[[-3.2129,  0.1729, -1.8117,  1.2714, -0.7187],
         [ 0.9727, -0.3181,  0.6488,  0.5503, -1.4991],
         [-0.4092,  0.6862,  0.0653, -0.1247, -0.0704],
         [ 0.3890,  0.4918,  0.0862,  0.8961, -1.1398],
         [ 0.1081,  0.6995,  0.5402, -0.3473,  0.9207]],

        [[ 0.0312, -1.1133,  1.2743, -0.2102,  0.4067],
         [ 0.0927,  0.3280,  0.3890, -0.3017,  0.1612],
         [ 0.4597, -0.5606,  0.6283, -1.1600,  0.9513],
         [ 0.2356,  1.3932, -0.6416, -0.4449, -0.1729],
         [-0.1579, -1.1701,  0.9381, -0.3644, -1.4191]]])

In [ ]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])
weights_named

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:848.)
  """Entry point for launching an IPython kernel.


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [ ]:
#When we already have a tensor and want to add names (but not change existing ones), we can call the method refine_names on it.

In [ ]:
img_named = img_t.refine_names(..., 'channels', 'rows','columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows','columns')
print("img named: ", img_named.shape, img_named.names)
print("batch named: ", batch_named.shape, batch_named.names)

img named:  torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named:  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [ ]:
weights_aligned = weights_named.align_as(img_named) #he method align_as returns a tensor with missing dimensions added and existing ones permuted to the right order
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [ ]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [ ]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [ ]:
#dtype

In [ ]:
double_points = torch.ones(10,2, dtype = torch.double)
short_points = torch.tensor([[1,2],[3,4]], dtype = torch.short)

In [ ]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [ ]:
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [ ]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [ ]:
double_points = torch.zeros(10, 2).to(torch.double)    #more convenient method
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [ ]:
points_64 = torch.rand(5, dtype=torch.double)   #rand initializes the tensor elements to random numbers between 0 and 1
points_short = points_64.to(torch.short)
points_64 * points_short # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [ ]:
#tensor API

In [ ]:
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
a = torch.ones(3,2) 
a_t = a.transpose(0,1)    #as the method of a tensor
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
#indexing into the storage

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [ ]:
points_storage = points.storage()
points_storage[0]

4.0

In [ ]:
points.storage()[1]

1.0

In [ ]:
#changing the value of a storage leads to changing the content of its referring tensor

In [ ]:
points = torch.tensor([[4.0, 1.0],[5.0,3.0],[2.0,1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
#Modifying stored values: In-place operations

In [ ]:
a = torch.ones(3,2)

In [ ]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
#Tensor metadata: Size, offset, and stride

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [ ]:
second_point.size()

torch.Size([2])

In [ ]:
second_point.shape

torch.Size([2])

In [ ]:
#The stride is a tuple indicating the number of elements in the storage that have to be skipped when the index is increased by 1 in each dimension

In [ ]:
points.stride()

(2, 1)

In [ ]:
second_point.stride()

(1,)